### model
model_name_or_path: /home/liangtao/Models/Qwen/Qwen2-0.5B
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
#lora_target: all
lora_target: q_proj,v_proj

### dataset
dataset: alpaca_moltrans_mit_mixed_nospace_train
template: qwen
cutoff_len: 2048
max_samples: 100000000000
overwrite_cache: true
#preprocessing_num_workers: 16
preprocessing_num_workers: 1
dataloader_num_workers: 4
data_sort_by: prompt_length
shuffle: false
### output
output_dir: saves/sft_lora/qwen205_moltrans_mit_mixed_nospace_lora_para3/
logging_steps: 100
save_steps: 20000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.02
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 5000


run_name: qwen205_moltrans_mit_mixed_nospace_lora_para3

# llamafactory-cli train examples/train_lora/qwen205/nospace/qwen205_moltrans_mit_mixed_nospace_lora_para3.yaml 2>&1 | tee -a logs/moltrans_mit_mixed_nospace_lora_para3.log

# accelerate launch --config_file examples/accelerate/fsdp_config_offload.yaml src/train.py examples/train_lora/qwen205/nospace/qwen205_moltrans_mit_mixed_nospace_lora_para3.yaml 2>&1 | tee -a logs/qwen205_moltrans_mit_mixed_nospace_lora_para3.log