# -*- coding: utf-8 -*-
# @project: LLaMA-Factory
# @filename: ppo_train.py
# @author: Karl Wu
# @contact: wlt1990@outlook.com
# @time: 2025/9/13 18:04
# https://chat.deepseek.com/a/chat/s/c8d54e56-f9a6-497c-b711-9afcd644c971
# https://chat.deepseek.com/a/chat/s/8498345c-ee59-413a-9771-17512fdafde0
# https://chat.deepseek.com/a/chat/s/b23ee767-7e3c-42c1-96d2-4e0cd5639883
# https://chat.deepseek.com/a/chat/s/9b9ecc23-57e2-44b5-af1f-435d196670fb

# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# !/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import json
import logging
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
from datetime import datetime

import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer
)
from peft import (
    LoraConfig,
    get_peft_model,
    PeftModel,
    TaskType,
    prepare_model_for_kbit_training
)
from trl import PPOTrainer, PPOConfig, AutoModelForCausalLMWithValueHead
from trl.core import LengthSampler
import numpy as np
from tqdm import tqdm
import rdkit.Chem as Chem
from rdkit.Chem import AllChem

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


@dataclass
class TrainingConfig:
    """Training configuration parameters"""
    model_path: str = "/mnt/e/CheckPoints/ChemicalFactory/output/qwen205_moltrans_mit_mixed_augm_nospace_full_para1"
    ppo_data_path: str = "/mnt/e/DataSets/Chemistry/ForwardPrediction/RLHF/mit_mixed/ppo/"
    ppo_data_file: str = "MIT_mixed_augm.json"
    ppo_model_output_path: str = "/mnt/e/CheckPoints/ChemicalFactory/output/qwen205_moltrans_mit_mixed_augm_rlhf_ppo_lora_para1"

    # Training parameters
    batch_size: int = 16
    mini_batch_size: int = 1
    gradient_accumulation_steps: int = 4
    learning_rate: float = 1.41e-5
    max_grad_norm: float = 0.5
    max_length: int = 256
    max_prompt_length: int = 64

    # PPO parameters
    ppo_epochs: int = 4
    init_kl_coef: float = 0.2
    target_kl: float = 6.0
    cliprange: float = 0.2
    cliprange_value: float = 0.2
    vf_coef: float = 0.1
    gamma: float = 1.0
    lam: float = 0.95

    # LoRA parameters
    lora_r: int = 16
    lora_alpha: int = 32
    lora_dropout: float = 0.05
    lora_target_modules: List[str] = field(default_factory=lambda: [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ])

    # Other parameters
    num_epochs: int = 10
    save_steps: int = 100
    logging_steps: int = 10
    warmup_steps: int = 10
    seed: int = 42
    device: str = "cuda:0" if torch.cuda.is_available() else "cpu"

    def __post_init__(self):
        """Create output directory if it doesn't exist"""
        os.makedirs(self.ppo_model_output_path, exist_ok=True)

        # Set full data path
        self.full_data_path = os.path.join(self.ppo_data_path, self.ppo_data_file)


class MolecularDataset(Dataset):
    """Dataset for molecular reaction prediction"""

    def __init__(self, data_path, tokenizer, max_length=256):
        self.tokenizer = tokenizer
        self.max_length = max_length

        # Load data
        with open(data_path, 'r', encoding='utf-8') as f:
            self.data = json.load(f)

        logger.info(f"Loaded {len(self.data)} samples from {data_path}")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]

        # Format the input message
        messages = [
            {"role": "user", "content": f"{item['instruction']}\n{item['input']}"}
        ]

        # Tokenize the input
        input_ids = self.tokenizer.apply_chat_template(
            messages,
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )

        return {
            "input_ids": input_ids.squeeze(0),
            "attention_mask": torch.ones_like(input_ids.squeeze(0)),
            "target_smiles": item["output"],
            "id": item["id"]
        }


def calculate_molecular_reward(generated_smiles: str, target_smiles: str) -> float:
    """
    Calculate reward based on molecular validity and similarity

    Args:
        generated_smiles: SMILES string generated by the model
        target_smiles: Target SMILES string from dataset

    Returns:
        float: Reward value (1.0, 0.1, or 0.0)
    """
    try:
        # Clean up the generated SMILES (remove special tokens, etc.)
        clean_gen = generated_smiles.strip()
        if '<|im_end|>' in clean_gen:
            clean_gen = clean_gen.split('<|im_end|>')[0]
        if '<|endoftext|>' in clean_gen:
            clean_gen = clean_gen.split('<|endoftext|>')[0]

        # Parse molecules
        gen_mol = Chem.MolFromSmiles(clean_gen)
        target_mol = Chem.MolFromSmiles(target_smiles)

        if gen_mol is None:
            # Invalid molecule
            return 0.0

        if target_mol is None:
            # Target is invalid (shouldn't happen with good data)
            logger.warning(f"Target SMILES is invalid: {target_smiles}")
            return 0.1  # Still reward for valid generation

        # Generate canonical SMILES for comparison
        gen_canonical = Chem.MolToSmiles(gen_mol, canonical=True)
        target_canonical = Chem.MolToSmiles(target_mol, canonical=True)

        if gen_canonical == target_canonical:
            # Exact match
            return 1.0
        else:
            # Valid but different molecule
            return 0.1

    except Exception as e:
        logger.error(f"Error calculating reward for {generated_smiles}: {e}")
        return 0.0


def collate_fn(batch):
    """Collate function for DataLoader"""
    input_ids = torch.nn.utils.rnn.pad_sequence(
        [item['input_ids'] for item in batch],
        batch_first=True,
        padding_value=0
    )

    attention_mask = torch.nn.utils.rnn.pad_sequence(
        [item['attention_mask'] for item in batch],
        batch_first=True,
        padding_value=0
    )

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'target_smiles': [item['target_smiles'] for item in batch],
        'id': [item['id'] for item in batch]
    }


def setup_lora_model(model, config):
    """Setup LoRA configuration for the model"""
    lora_config = LoraConfig(
        r=config.lora_r,
        lora_alpha=config.lora_alpha,
        lora_dropout=config.lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
        target_modules=config.lora_target_modules,
    )

    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    return model


def train_ppo(config):
    """Main training function for PPO"""

    # Set random seed
    torch.manual_seed(config.seed)
    np.random.seed(config.seed)

    # Setup device
    device = torch.device(config.device)
    logger.info(f"Using device: {device}")

    # Load tokenizer
    logger.info("Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(config.model_path)
    tokenizer.pad_token = tokenizer.eos_token

    # 使用 trl 的简化方式
    model = AutoModelForCausalLMWithValueHead.from_pretrained(
        config.model_path,
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto",
        trust_remote_code=True,
        peft_config=LoraConfig(
            r=config.lora_r,
            lora_alpha=config.lora_alpha,
            lora_dropout=config.lora_dropout,
            bias="none",
            task_type=TaskType.CAUSAL_LM,
            target_modules=config.lora_target_modules,
        )
    )

    # 参考模型（不应用 LoRA）
    ref_model = AutoModelForCausalLMWithValueHead.from_pretrained(
        config.model_path,
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto",
        trust_remote_code=True
    )

    # 冻结参考模型的参数
    for param in ref_model.parameters():
        param.requires_grad = False

    # 检查是否有可训练的参数
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    logger.info(f"Number of trainable parameters: {trainable_params}")

    if trainable_params == 0:
        raise ValueError("No trainable parameters found! Check LoRA configuration.")

    # Create dataset and dataloader
    logger.info("Creating dataset and dataloader...")
    dataset = MolecularDataset(config.full_data_path, tokenizer, config.max_length)
    dataloader = DataLoader(
        dataset,
        batch_size=config.batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=4
    )

    # Configure PPO
    ppo_config = PPOConfig(
        model_name=config.model_path,
        learning_rate=config.learning_rate,
        batch_size=config.batch_size,
        mini_batch_size=config.mini_batch_size,
        gradient_accumulation_steps=config.gradient_accumulation_steps,
        ppo_epochs=config.ppo_epochs,
        init_kl_coef=config.init_kl_coef,
        target_kl=config.target_kl,
        cliprange=config.cliprange,
        cliprange_value=config.cliprange_value,
        vf_coef=config.vf_coef,
        gamma=config.gamma,
        lam=config.lam,
        optimize_cuda_cache=True,
        log_with=None,
        seed=config.seed,
    )

    # 修改这里：传递参考模型给 PPOTrainer
    ppo_trainer = PPOTrainer(
        config=ppo_config,
        model=model,
        ref_model=ref_model,  # 传递参考模型
        tokenizer=tokenizer,
        dataset=dataset,
    )

    # Training loop
    logger.info("Starting PPO training...")

    for epoch in range(config.num_epochs):
        epoch_rewards = []
        epoch_kl_divergences = []

        progress_bar = tqdm(dataloader, desc=f"Epoch {epoch + 1}/{config.num_epochs}")

        for batch_idx, batch in enumerate(progress_bar):
            # Move batch to device
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            target_smiles = batch['target_smiles']

            # 修复：将批次转换为列表形式
            query_tensors = []
            for i in range(len(input_ids)):
                # 获取实际长度（去除填充）
                actual_length = attention_mask[i].sum().item()
                query_tensor = input_ids[i][:actual_length]
                query_tensors.append(query_tensor)

            # 生成响应
            generation_kwargs = {
                "max_new_tokens": config.max_length,
                "min_length": -1,
                "top_k": 0.0,
                "top_p": 1.0,
                "do_sample": True,
                "pad_token_id": tokenizer.eos_token_id,
                "eos_token_id": tokenizer.eos_token_id,
            }

            response_tensors = ppo_trainer.generate(
                query_tensors,  # 直接传递列表
                return_prompt=False,
                **generation_kwargs
            )

            # 解码响应
            generated_texts = []
            for response in response_tensors:
                gen_text = tokenizer.decode(response, skip_special_tokens=True)
                generated_texts.append(gen_text)

            # Calculate rewards
            rewards = []
            for gen_text, target_smile in zip(generated_texts, target_smiles):
                reward = calculate_molecular_reward(gen_text, target_smile)
                rewards.append(reward)

            rewards = torch.tensor(rewards, dtype=torch.float32).to(device)
            epoch_rewards.extend(rewards.cpu().numpy())

            # 修复：将批次转换为列表形式
            query_tensors_list = []
            for i in range(len(input_ids)):
                actual_length = attention_mask[i].sum().item()
                query_tensor = input_ids[i][:actual_length]
                query_tensors_list.append(query_tensor)

            # 确保 response_tensors 是列表
            if not isinstance(response_tensors, list):
                response_tensors = [response_tensors]

            # 确保 rewards 是 FloatTensor 列表
            rewards_list = []
            for reward in rewards:
                if isinstance(reward, torch.Tensor):
                    rewards_list.append(reward.float().to(device))
                else:
                    rewards_list.append(torch.tensor(reward, dtype=torch.float32, device=device))

            # Run PPO step
            stats = ppo_trainer.step(
                query_tensors_list,  # 张量列表
                response_tensors,  # 张量列表
                rewards_list  # FloatTensor 列表
            )

            if stats is not None:
                epoch_kl_divergences.append(stats['objective/kl'])

            # Update progress bar
            avg_reward = np.mean(epoch_rewards[-len(rewards):]) if epoch_rewards else 0
            progress_bar.set_postfix({
                'avg_reward': f'{avg_reward:.3f}',
                'batch_reward': f'{rewards.mean().item():.3f}'
            })

            # Logging
            if batch_idx % config.logging_steps == 0:
                logger.info(
                    f"Epoch {epoch + 1}, Batch {batch_idx}: "
                    f"Avg Reward: {np.mean(epoch_rewards):.3f}, "
                    f"KL Div: {np.mean(epoch_kl_divergences) if epoch_kl_divergences else 0:.3f}"
                )

            # Save checkpoint
            if batch_idx % config.save_steps == 0 and batch_idx > 0:
                checkpoint_path = os.path.join(
                    config.ppo_model_output_path,
                    f"checkpoint-epoch{epoch + 1}-batch{batch_idx}"
                )
                ppo_trainer.save_pretrained(checkpoint_path)
                logger.info(f"Saved checkpoint to {checkpoint_path}")

        # Save epoch checkpoint
        epoch_checkpoint_path = os.path.join(
            config.ppo_model_output_path,
            f"epoch-{epoch + 1}"
        )
        ppo_trainer.save_pretrained(epoch_checkpoint_path)
        logger.info(f"Saved epoch {epoch + 1} checkpoint to {epoch_checkpoint_path}")

        # Log epoch statistics
        logger.info(
            f"Epoch {epoch + 1} completed: "
            f"Average Reward: {np.mean(epoch_rewards):.3f}, "
            f"Average KL Divergence: {np.mean(epoch_kl_divergences):.3f}"
        )

    # Save final model
    final_model_path = os.path.join(config.ppo_model_output_path, "final_model")
    ppo_trainer.save_pretrained(final_model_path)
    logger.info(f"Training completed. Final model saved to {final_model_path}")


def main():
    # Create config
    config = TrainingConfig(
        model_path=args.model_path,
        ppo_data_path=args.ppo_data_path,
        ppo_data_file=args.ppo_data_file,
        ppo_model_output_path=args.ppo_model_output_path,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        max_length=args.max_length,
        num_epochs=args.num_epochs,
        seed=args.seed,
    )

    # Setup logging to file
    log_file = os.path.join(config.ppo_model_output_path, f"training_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log")
    file_handler = logging.FileHandler(log_file)
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(file_handler)

    logger.info("Starting PPO training with configuration:")
    for key, value in vars(config).items():
        logger.info(f"  {key}: {value}")

    # Start training
    try:
        train_ppo(config)
        logger.info("Training completed successfully!")
    except Exception as e:
        logger.error(f"Training failed with error: {e}")
        raise


if __name__ == "__main__":
    """Main function"""
    # Parse command line arguments or use defaults
    import argparse

    parser = argparse.ArgumentParser(description="PPO Training for Molecular Generation")

    # Add arguments for all config parameters
    parser.add_argument('--model_path', type=str, default=TrainingConfig.model_path)
    parser.add_argument('--ppo_data_path', type=str, default=TrainingConfig.ppo_data_path)
    parser.add_argument('--ppo_data_file', type=str, default=TrainingConfig.ppo_data_file)
    parser.add_argument('--ppo_model_output_path', type=str, default=TrainingConfig.ppo_model_output_path)

    parser.add_argument('--batch_size', type=int, default=TrainingConfig.batch_size)
    parser.add_argument('--learning_rate', type=float, default=TrainingConfig.learning_rate)
    parser.add_argument('--max_length', type=int, default=TrainingConfig.max_length)
    parser.add_argument('--num_epochs', type=int, default=TrainingConfig.num_epochs)
    parser.add_argument('--seed', type=int, default=TrainingConfig.seed)

    args = parser.parse_args()
    main()