### model
model_name_or_path: /home/liangtao/Models/Qwen/Qwen2-0.5B
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
#dataset: alpaca_molecular_transformer_mit_mixed
dataset: alpaca_moltrans_mit_mixed_space_train
template: qwen
cutoff_len: 2048
max_samples: 10000000
overwrite_cache: true
#preprocessing_num_workers: 16
preprocessing_num_workers: 1
dataloader_num_workers: 4

### output
#legacy output_dir: saves/Qwen2-0.5B-Molecular-Transformer-MIT-Mixed/lora/sft
output_dir: saves/sft_lora/qwen205_moltrans_mit_mixed_space_lora_para1_resume
logging_steps: 10
save_steps: 10000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: saves/sft_lora/qwen205_moltrans_mit_mixed_augm_space_lora_para1/checkpoint-601281

### eval
val_size: 0.02
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 2000


run_name: qwen205_moltrans_mit_mixed_space_lora_para1_resume


#legacy: llamafactory-cli train examples/train_lora/qwen205/space/qwen205_moltrans_mit_mixed_space_lora_para1_resume.yaml | tee -a logs/qwen205_moltrans_mit_mixed_space_lora_para1_resume.log
